In [1]:
%reload_ext fusedwind

In [2]:
from openmdao.api import Component
import json
from fusedwind.core.FUSEDobj import FUSEDobj, flatten
import numpy as np

In [3]:
windio_obj = {
    'layout': [
        {
            'name': 'wt1',
            'hub_height': 80.,
            'rotor_diameter': 80.,
            'position': {'x':6400, 'y':23232},
            'power': 2000.,
            'array': [1,2,3,4],
            'c_t_curve': np.array([np.arange(4,25), np.arange(4,25)**3.0])
        },
        {
            'name': 'wt2',
            'hub_height': 70.,
            'rotor_diameter': 80.,
            'position': {'x':6400, 'y':23332,"another":{'layer':12}},
            'power': 2000.,
            'array': [1,2,3,4],
            'c_t_curve': np.array([np.arange(4,25), np.arange(4,25)**3.0])

        },            
    ]
}

In [4]:
flatten(windio_obj)

{'layout:wt1:array': [1, 2, 3, 4],
 'layout:wt1:c_t_curve': array([[  4.00000000e+00,   5.00000000e+00,   6.00000000e+00,
           7.00000000e+00,   8.00000000e+00,   9.00000000e+00,
           1.00000000e+01,   1.10000000e+01,   1.20000000e+01,
           1.30000000e+01,   1.40000000e+01,   1.50000000e+01,
           1.60000000e+01,   1.70000000e+01,   1.80000000e+01,
           1.90000000e+01,   2.00000000e+01,   2.10000000e+01,
           2.20000000e+01,   2.30000000e+01,   2.40000000e+01],
        [  6.40000000e+01,   1.25000000e+02,   2.16000000e+02,
           3.43000000e+02,   5.12000000e+02,   7.29000000e+02,
           1.00000000e+03,   1.33100000e+03,   1.72800000e+03,
           2.19700000e+03,   2.74400000e+03,   3.37500000e+03,
           4.09600000e+03,   4.91300000e+03,   5.83200000e+03,
           6.85900000e+03,   8.00000000e+03,   9.26100000e+03,
           1.06480000e+04,   1.21670000e+04,   1.38240000e+04]]),
 'layout:wt1:hub_height': 80.0,
 'layout:wt1:name': 'wt

In [5]:
wf = FUSEDobj(windio_obj)

Return the values of a FUSEDobj

In [6]:
list(wf.layout.wt1.values())

[[[  4.00000000e+00   5.00000000e+00   6.00000000e+00   7.00000000e+00
     8.00000000e+00   9.00000000e+00   1.00000000e+01   1.10000000e+01
     1.20000000e+01   1.30000000e+01   1.40000000e+01   1.50000000e+01
     1.60000000e+01   1.70000000e+01   1.80000000e+01   1.90000000e+01
     2.00000000e+01   2.10000000e+01   2.20000000e+01   2.30000000e+01
     2.40000000e+01]
  [  6.40000000e+01   1.25000000e+02   2.16000000e+02   3.43000000e+02
     5.12000000e+02   7.29000000e+02   1.00000000e+03   1.33100000e+03
     1.72800000e+03   2.19700000e+03   2.74400000e+03   3.37500000e+03
     4.09600000e+03   4.91300000e+03   5.83200000e+03   6.85900000e+03
     8.00000000e+03   9.26100000e+03   1.06480000e+04   1.21670000e+04
     1.38240000e+04]], 80.0, {
   "y": 23232,
   "x": 6400
 }, [1, 2, 3, 4], 80.0, 2000.0, wt1]

Return all the keys of a FUSEDobj

In [7]:
list(wf.layout.wt1.keys())

['c_t_curve',
 'hub_height',
 'position',
 'array',
 'rotor_diameter',
 'power',
 'name']

The representation of the object is still the nested dictionary, but it's for your eyes only 

In [8]:
wf.layout.wt2

{
  "c_t_curve": [
    [
      4.0,
      5.0,
      6.0,
      7.0,
      8.0,
      9.0,
      10.0,
      11.0,
      12.0,
      13.0,
      14.0,
      15.0,
      16.0,
      17.0,
      18.0,
      19.0,
      20.0,
      21.0,
      22.0,
      23.0,
      24.0
    ],
    [
      64.0,
      125.0,
      216.0,
      343.0,
      512.0,
      729.0,
      1000.0,
      1331.0,
      1728.0,
      2197.0,
      2744.0,
      3375.0,
      4096.0,
      4913.0,
      5832.0,
      6859.0,
      8000.0,
      9261.0,
      10648.0,
      12167.0,
      13824.0
    ]
  ],
  "hub_height": 70.0,
  "position": {
    "y": 23332,
    "another": {
      "layer": 12
    },
    "x": 6400
  },
  "array": [
    1,
    2,
    3,
    4
  ],
  "power": 2000.0,
  "rotor_diameter": 80.0,
  "name": "wt2"
}

In [9]:
wf.layout.wt2.c_t_curve._type

'ndarray'

You can reconstruct the nested structure using the `.nest()` method

In [10]:
ly = wf.layout.nest()
ly

[{'array': [1, 2, 3, 4],
  'c_t_curve': array([[  4.00000000e+00,   5.00000000e+00,   6.00000000e+00,
            7.00000000e+00,   8.00000000e+00,   9.00000000e+00,
            1.00000000e+01,   1.10000000e+01,   1.20000000e+01,
            1.30000000e+01,   1.40000000e+01,   1.50000000e+01,
            1.60000000e+01,   1.70000000e+01,   1.80000000e+01,
            1.90000000e+01,   2.00000000e+01,   2.10000000e+01,
            2.20000000e+01,   2.30000000e+01,   2.40000000e+01],
         [  6.40000000e+01,   1.25000000e+02,   2.16000000e+02,
            3.43000000e+02,   5.12000000e+02,   7.29000000e+02,
            1.00000000e+03,   1.33100000e+03,   1.72800000e+03,
            2.19700000e+03,   2.74400000e+03,   3.37500000e+03,
            4.09600000e+03,   4.91300000e+03,   5.83200000e+03,
            6.85900000e+03,   8.00000000e+03,   9.26100000e+03,
            1.06480000e+04,   1.21670000e+04,   1.38240000e+04]]),
  'hub_height': 80.0,
  'name': 'wt1',
  'position': {'x': 640

In [11]:
ly[0]['hub_height']

80.0

You can resolve addresses with wildecards. This should be useful to connect things together.

In [12]:
for k in wf.resolves('layout:*:hub_height'):
    print(k.address, '=', k.value)

layout:wt1:hub_height = 80.0
layout:wt2:hub_height = 70.0


You can set a new value, and this will change the flatten dict under the hood

In [13]:
new_value = 90.0
wf.layout.wt1.hub_height.value = new_value
# Check the the flat_dict at the root has bee updated
assert wf._flat_dict['layout:wt1:hub_height'] == new_value
print(wf.layout.wt1.hub_height, 
      wf._flat_dict['layout:wt1:hub_height'])

90.0 90.0


In [14]:
for k in wf.resolves('*:*:hub_height'):
    print(k.address, '=', k.value)

You can even directly assign the value to the FUSEDobj, it will figure out how to propagate the values in the root flatten dictionary

In [15]:
new_value = 110.0
wf.layout.wt1.hub_height = new_value
# Check the the flat_dict at the root has bee updated
assert wf._flat_dict['layout:wt1:hub_height'] == new_value
print(wf.layout.wt1.hub_height, 
      wf._flat_dict['layout:wt1:hub_height'])

110.0 110.0


Even nested dictionaries!

In [16]:
wf.layout.wt1 = {
  "hub_height": 85.0,
  "power": 2200.0,
  "rotor_diameter": 100.0,
  "position": {
    "x": 6400,
    "y": 23222,
  },
  "name": "wt1"
}

In [17]:
for k in wf.resolves('layout:wt2:*'):
    print(k.address,'=', k)

layout:wt2:c_t_curve = [[  4.00000000e+00   5.00000000e+00   6.00000000e+00   7.00000000e+00
    8.00000000e+00   9.00000000e+00   1.00000000e+01   1.10000000e+01
    1.20000000e+01   1.30000000e+01   1.40000000e+01   1.50000000e+01
    1.60000000e+01   1.70000000e+01   1.80000000e+01   1.90000000e+01
    2.00000000e+01   2.10000000e+01   2.20000000e+01   2.30000000e+01
    2.40000000e+01]
 [  6.40000000e+01   1.25000000e+02   2.16000000e+02   3.43000000e+02
    5.12000000e+02   7.29000000e+02   1.00000000e+03   1.33100000e+03
    1.72800000e+03   2.19700000e+03   2.74400000e+03   3.37500000e+03
    4.09600000e+03   4.91300000e+03   5.83200000e+03   6.85900000e+03
    8.00000000e+03   9.26100000e+03   1.06480000e+04   1.21670000e+04
    1.38240000e+04]]
layout:wt2:hub_height = 70.0
layout:wt2:position:y = 23332
layout:wt2:position:another:layer = 12
layout:wt2:position:x = 6400
layout:wt2:array = [1, 2, 3, 4]
layout:wt2:rotor_diameter = 80.0
layout:wt2:power = 2000.0
layout:wt2:name = 

In [18]:
list(wf.layout.resolves('*:hub_height'))

[85.0, 70.0]

In [19]:
wf._flat_dict

{'layout:wt1:array': [1, 2, 3, 4],
 'layout:wt1:c_t_curve': array([[  4.00000000e+00,   5.00000000e+00,   6.00000000e+00,
           7.00000000e+00,   8.00000000e+00,   9.00000000e+00,
           1.00000000e+01,   1.10000000e+01,   1.20000000e+01,
           1.30000000e+01,   1.40000000e+01,   1.50000000e+01,
           1.60000000e+01,   1.70000000e+01,   1.80000000e+01,
           1.90000000e+01,   2.00000000e+01,   2.10000000e+01,
           2.20000000e+01,   2.30000000e+01,   2.40000000e+01],
        [  6.40000000e+01,   1.25000000e+02,   2.16000000e+02,
           3.43000000e+02,   5.12000000e+02,   7.29000000e+02,
           1.00000000e+03,   1.33100000e+03,   1.72800000e+03,
           2.19700000e+03,   2.74400000e+03,   3.37500000e+03,
           4.09600000e+03,   4.91300000e+03,   5.83200000e+03,
           6.85900000e+03,   8.00000000e+03,   9.26100000e+03,
           1.06480000e+04,   1.21670000e+04,   1.38240000e+04]]),
 'layout:wt1:hub_height': 85.0,
 'layout:wt1:name': 'wt

In [20]:
wf.layout.wt1.array.value

[1, 2, 3, 4]

In [21]:
wf.layout.wt1.array

[1, 2, 3, 4]

In [22]:
(wf.layout.wt1.hub_height + wf.layout.wt2.hub_height)/2.

77.5

In [23]:
wf.layout.wt1.hub_height / 2.0

42.5

In [24]:
wf.layout.wt1.hub_height == wf.layout.wt2.hub_height

False

In [25]:
wf.layout.wt1.hub_height == wf.layout.wt2.hub_height + 15

True

In [26]:
wf.layout.wt1.hub_height <= wf.layout.wt2.hub_height

False

In [27]:
wf.layout.wt1.hub_height >= wf.layout.wt2.hub_height

True

In [28]:
wf.layout.wt1.hub_height / wf.layout.wt2.hub_height

1.2142857142857142

In [29]:
wf.layout.wt1.c_t_curve**2.

array([[  1.60000000e+01,   2.50000000e+01,   3.60000000e+01,
          4.90000000e+01,   6.40000000e+01,   8.10000000e+01,
          1.00000000e+02,   1.21000000e+02,   1.44000000e+02,
          1.69000000e+02,   1.96000000e+02,   2.25000000e+02,
          2.56000000e+02,   2.89000000e+02,   3.24000000e+02,
          3.61000000e+02,   4.00000000e+02,   4.41000000e+02,
          4.84000000e+02,   5.29000000e+02,   5.76000000e+02],
       [  4.09600000e+03,   1.56250000e+04,   4.66560000e+04,
          1.17649000e+05,   2.62144000e+05,   5.31441000e+05,
          1.00000000e+06,   1.77156100e+06,   2.98598400e+06,
          4.82680900e+06,   7.52953600e+06,   1.13906250e+07,
          1.67772160e+07,   2.41375690e+07,   3.40122240e+07,
          4.70458810e+07,   6.40000000e+07,   8.57661210e+07,
          1.13379904e+08,   1.48035889e+08,   1.91102976e+08]])

slicing also works

In [30]:
wf.layout.wt1.c_t_curve[:,0]

array([  4.,  64.])

In [31]:
wf.layout.wt1.c_t_curve[0,0] = 5.0

In [32]:
wf.layout.wt1.c_t_curve[:,0]

array([  5.,  64.])

In [33]:
round(wf.layout.wt1.hub_height)

85